import "dotenv/config";
import { runQuery } from "./DB/DB.js";

const insertCard = async (values) => {
  const query = "INSERT IGNORE INTO cards(color,text) values " + values;
  return runQuery(query, []);
};
const whiteList = [
  "A bigger, blacker dick.",
  "The mere concept of Applebee's.",
  "A sad fat dragon with no friends.",
  "Catastrophic urethral trauma.",
  "Hillary Clinton's death stare.",
  "Existing.",
  "A piñata full of scorpions.",
  "Mooing.",
  "Swiftly achieving orgasm.",
  "Daddy's belt.",
  "Me.",
  "Double penetration.",
  "Weapons-grade plutonium.",
  "Some really fucked-up shit.",
  "Subduing a grizzly bear and making her your wife.",
  "Rising from the grave.",
  "The mixing of the races.",
  "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
  "Scrotal frostbite.",
  "All of this blood.",
  "Loki, the trickster god.",
  "Whining like a little bitch.",
  "Pumping out a baby every nine months.",
  "Tongue.",
  "Finding Waldo.",
  "Upgrading homeless people to mobile hotspots.",
  "Wearing an octopus for a hat.",
  "An unhinged ferris wheel rolling toward the sea.",
  "Living in a trashcan.",
  "The corporations.",
  "A magic hippie love cloud.",
  "Fuck Mountain.",
  "Survivor's guilt.",
  "Getting hilariously gang-banged by the Blue Man Group.",
  "Jeff Goldblum.",
  "Making a friend.",
  "A soulful rendition of 'Ol' Man River.'",
  "Intimacy problems.",
  "A sweaty, panting leather daddy.",
  "Spring break!",
  "Being awesome at sex.",
  "Dining with cardboard cutouts of the cast of 'Friends.'",
  "Another shot of morphine.",
  "Beefin' over turf.",
  "A squadron of moles wearing aviator goggles.",
  "Bullshit.",
  "Pretty Pretty Princess Dress-Up Board Game®.",
  "The new Radiohead album.",
  "An army of skeletons.",
  "A man in yoga pants with a ponytail and feather earrings.",
  "Mild autism.",
  "Nunchuck moves.",
  "Whipping a disobedient slave.",
  "An ether-soaked rag.",
  "A sweet spaceship.",
  "A 55-gallon drum of lube.",
  "Special musical guest, Cher.",
  "The human body.",
  "Boris the Soviet Love Hammer.",
  "The grey nutrient broth that sustains Mitt Romney.",
  "Tiny nipples.",
  "Oncoming traffic.",
  "A dollop of sour cream.",
  "A slightly shittier parallel universe.",
  "My first kill.",
  "Graphic violence, adult language, and some sexual content.",
  "Fetal alcohol syndrome.",
  "The day the birds attacked.",
  "One Ring to rule them all.",
  "Grandpa's ashes.",
  "Basic human decency.",
  "A Burmese tiger pit.",
  "Death by Steven Seagal.",
  "The Google.",
  "Power.",
  "That ass.",
  "Nothing.",
  "Shutting the fuck up.",
  "The primal, ball-slapping sex your parents are having right now.",
  "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
  "Cock.",
  "A cop who is also a dog.",
  "Dying alone and in pain.",
  "Gay aliens.",
  "The way white people is.",
  "Reverse cowgirl.",
  "The Quesadilla Explosion Salad from Chili’s.",
  "Actually getting shot, for real.",
  "Not having sex.",
  "Vietnam flashbacks.",
  "Running naked through a mall, pissing and shitting everywhere.",
  "Warm, velvety muppet sex.",
  "Self-flagellation.",
  "The systematic destruction of an entire people and their way of life.",
  "Samuel L. Jackson.",
  "A boo-boo.",
  "Going around punching people.",
  "The entire Internet.",
  "Some kind of bird-man.",
  "Chugging a lava lamp.",
  "Having sex on top of a pizza.",
  "Indescribable loneliness.",
  "An ass disaster.",
  "All my friends dying.",
  "Putting an entire peanut buter and jelly sandwich into the VCR.",
  "Spending lots of money.",
  "Some douche with an acoustic guitar.",
  "Flying robots that kill people.",
  "A greased-up Matthew McConaughey.",
  "An unstoppable wave of fire ants.",
  "Not contributing to society in any meaningful way.",
  "An all-midget production of Shakespeare’s Richard III.",
  "Screaming like a maniac.",
  "The moist, demanding chasm of his mouth.",
  "Filling every orifice with butterscotch pudding.",
  "Unlimited soup, salad, and breadsticks.",
  "Crying into the pages of Sylvia Plath.",
  "Velcro.",
  "A PowerPoint presentation.",
  "A surprising amount of hair.",
  "Eating Tom Selleck’s mustache to gain his powers.",
  "Roland the Farter, flatulist to the king.",
  "A pile of squirming bodies.",
  "Buying the right pants to be cool.",
  "Blood farts.",
  "Three months in the hole.",
  "A botched circumcision.",
  "The Land of Chocolate.",
  "Slapping a racist old lady.",
  "A lamprey swimming up the toilet and latching onto your taint.",
  "Jumping out at people.",
  "A black male in his early 20s, last seen wearing a hoodie.",
  "Mufasa’s death scene.",
  "Bill Clinton, naked on a bearskin rug with a saxophone.",
  "Demonic possession.",
  "The Harlem Globetrotters.",
  "Vomiting mid-blowjob.",
  "My manservant, Claude.",
  "Having shotguns for legs.",
  "Letting everyone down.",
  "A spontaneous conga line.",
  "A vagina that leads to another dimension.",
  "Disco fever.",
  "Getting your dick stuck in a Chinese finger trap with another dick.",
  "Fisting.",
  "The thin veneer of situational causality that underlies porn.",
  "Girls that always be textin’.",
  "Blowing some dudes in an alley.",
  "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.",
  "Sneezing, farting, and coming at the same time.",
  "Snotsicles.",
  "Syrupy sex with a maple tree.",
  "Homo milk.",
  "Heritage minutes.",
  "Burning down the White House.",
  "A Molson muscle.",
  "Schmirler the Curler.",
  "The CBC.",
  "Tim Hortons.",
  "Naked News.",
  "Terry Fox's prosthetic leg.",
  "Mr. Dressup.",
  "The Royal Canadian Mounted Police.",
  "Being Canadian.",
  "An icy hand job from an Edmonton hooker.",
  "The Offical Languages Act. La Loi sur les langues officielles.",
  "Graham Greene playing the same First Nations character on every TV show.",
  "Quintland.",
  "Don Cherry's wardrobe.",
  "Canada: America's hat.",
  "The Front de Libération du Québec.",
  "Stephen Harper.",
  "The Famous Five.",
  "Poutine.",
  "Newfies.",
  "Killing a Moose with your bare hands.",
  "Karla Homolka.",
  "Elf cum.",
  "Gift-wrapping a live hamster.",
  "Mall Santa.",
  "Santa's heavy sack.",
  "My hot cousin.",
  "Fucking up 'Silent Night' in front of 300 parents.",
  "Taking down Santa with a surface-to-air missile.",
  "The tiny, calloused hands of the Chinese children that made this card.",
  "Eating an entire snowman.",
  "Several intertwining love stories featuring Hugh Grant.",
  "Clearing a bloody path through Walmart with a scimitar.",
  "Another shitty year.",
  "A visually arresting turtleneck.",
  "A toxic family environment.",
  "Socks.",
  "Pretending to be happy.",
  "A Hungry-Man Frozen Christmas Dinner for One.",
  "Whatever Kwanzaa is supposed to be about.",
  "Krampus, the Austrian Christmas monster.",
  "A Christmas stocking full of coleslaw.",
  "Space Jam on VHS.",
  "Immaculate conception.",
  "The Star Wars Holiday Special.",
  "Robert Downey, Jr",
  "Horse meat",
  "A really cool hat",
  "Kim Jong-il",
  "A stray pube",
  "Jewish fraternities",
  "The token minority",
  "Doin' it in the butt",
  "Feeding Rosie O'Donnell",
  "Teaching a robot to love",
  "A can of whoop-ass",
  "A windmill full of corpses",
  "Count Chocula",
  "Wearing underwear inside-out to avoid doing laundry",
  "A death ray",
  "The glass ceiling",
  "A cooler full of organs",
  "The American Dream",
  "Keg stands",
  "When you fart and a little bit comes out",
  "Take-backsies",
  "Dead babies",
  "Foreskin",
  "Saxophone solos",
  "Italians",
  "A fetus",
  "Firing a rifle into the air while balls deep in a squealing hog",
  "Dick Cheney",
  "Amputees",
  "Eugenics",
  "My relationship status",
  "Christopher Walken",
  "Bees?",
  "Harry Potter erotica",
  "College",
  "Getting drunk on mouthwash",
  "Nazis",
  "8 oz of sweet Mexican black-tar heroin",
  "Stephen Hawking talking dirty",
  "A Gypsy curse",
  "A moment of silence",
  "A sausage festival",
  "An honest cop with nothing left to lose",
  "Famine",
  "Flesh-eating bacteria",
  "Flying sex snakes",
  "Not giving a shit about the Third World",
  "Sexting",
  "Sniffing glue",
  "Porn stars",
  "Raping and pillaging",
  "72 virgins",
  "A drive-by shooting",
  "A time travel paradox",
  "Authentic Mexican cuisine",
  "Bling",
  "Consultants",
  "Crippling debt",
  "Daddy issues",
  "The Donald Trump Seal of Approval",
  "Dropping a chandelier on your enemies and riding the rope up",
  "Former President George W. Bush",
  "Full frontal nudity",
  "Hormone injections",
  "Laying an egg",
  "Getting naked and watching Nickelodeon",
  "Pretending to care",
  "Public ridicule",
  "Sharing needles",
  "Boogers",
  "The inevitable heat death of the universe",
  "The miracle of childbirth",
  "The Rapture",
  "Whipping it out",
  "White privilege",
  "Wifely duties",
  "The Hamburglar",
  "AXE Body Spray",
  "The Blood of Christ",
  "Horrifying laser hair removal accidents",
  "BATMAN!!!",
  "Agriculture",
  "A robust mongoloid",
  "Natural selection",
  "Coat hanger abortions",
  "Eating all of the cookies before the AIDS bake-sale",
  "Michelle Obama's arms",
  "The World of Warcraft",
  "Swooping",
  "Obesity",
  "A homoerotic volleyball montage",
  "Lockjaw",
  "A mating display",
  "Testicular torsion",
  "All-you-can-eat shrimp for $4.99",
  "Domino's Oreo Dessert Pizza",
  "Kanye West",
  "Hot cheese",
  "Raptor attacks",
  "Taking off your shirt",
  "Smegma",
  "Alcoholism",
  "A middle-aged man on roller skates",
  "The Care Bear Stare",
  "Bingeing and purging",
  "Oversized lollipops",
  "Self-loathing",
  "Children on leashes",
  "Half-assed foreplay",
  "The Holy Bible",
  "German dungeon porn",
  "Being on fire",
  "Teenage pregnancy",
  "Gandhi",
  "Leaving an awkward voicemail",
  "Uppercuts",
  "Customer service representatives",
  "An erection that lasts longer than four hours",
  "My genitals",
  "Picking up girls at the abortion clinic",
  "Science",
  "Not reciprocating oral sex",
  "Flightless birds",
  "A good sniff",
  "Waterboarding",
  "A balanced breakfast",
  "Historically black colleges",
  "Actually taking candy from a baby",
  "The Make-A-Wish Foundation",
  "A clandestine butt scratch",
  "The Amish",
  "The Chinese gymnastics team",
  "Switching to Geico",
  "Peeing a little bit",
  "Home video of Oprah sobbing into a Lean Cuisine",
  "Nocturnal emissions",
  "The Jews",
  "My humps",
  "Powerful thighs",
  "Winking at old people",
  "Mr. Clean, right behind you",
  "A gentle caress of the inner thigh",
  "Sexual tension",
  "The forbidden fruit",
  "Skeletor",
  "Fancy Feast",
  "Being rich",
  "Sweet, sweet vengeance",
  "Republicans",
  "A gassy antelope",
  "Natalie Portman",
  "Copping a feel",
  "Kamikaze pilots",
  "Sean Connery",
  "The homosexual agenda",
  "The hardworking Mexican",
  "A falcon with a cap on its head",
  "Altar boys",
  "The Kool-Aid Man",
  "Getting so angry that you pop a boner",
  "Free samples",
  "A big hoopla about nothing",
  "Doing the right thing",
  "The Three-Fifths compromise",
  "Lactation",
  "World peace",
  "RoboCop",
  "Chutzpah",
  "Justin Bieber",
  "Oompa-Loompas",
  "Genetically engineered super-soldiers",
  "Puberty",
  "Ghosts",
  "An asymmetric boob job",
  "Vigorous jazz hands",
  "Fingering",
  "Glenn Beck catching his scrotum on a curtain hook",
  "GoGurt",
  "Police brutality",
  "John Wilkes Booth",
  "Preteens",
  "Scalping",
  "Stifling a giggle at the mention of Hutus and Tutsis",
  "Tweeting",
  "Darth Vader",
  "A sad handjob",
  "Exactly what you'd expect",
  "Expecting a burp and vomiting on the floor",
  "Adderall",
  "Embryonic stem cells",
  "Tasteful side-boob",
  "Panda sex",
  "An icepick lobotomy",
  "Tom Cruise",
  "Mouth herpes",
  "Sperm whales",
  "Homeless people",
  "Third base",
  "Incest",
  "Pac-Man uncontrollably guzzling cum",
  "A mime having a stroke",
  "Hulk Hogan",
  "God",
  "Scrubbing under the folds",
  "Golden showers",
  "Emotions",
  "Licking things to claim them as your own",
  "Pabst Blue Ribbon",
  "The placenta",
  "Spontaneous human combustion",
  "Friends with benefits",
  "Finger painting",
  "The hiccups",
  "Dying of dysentery",
  "My inner demons",
  "A Super Soaker full of cat pee",
  "Aaron Burr",
  "Words, words, words",
  "The chronic",
  "Dead parents",
  "Object permanence",
  "Opposable thumbs",
  "Racially-biased SAT questions",
  "Jibber-jabber",
  "Chainsaws for hands",
  "Nicolas Cage",
  "Child beauty pageants",
  "Explosions",
  "Shapeshifters",
  "Glenn Beck being harried by a swarm of buzzards",
  "Repression",
  "Roofies",
  "My vagina",
  "Assless chaps",
  "A murder most foul",
  "Giving 110 percent",
  "Her Royal Highness, Queen Elizabeth II",
  "The Trail of Tears",
  "Being marginalized",
  "Goblins",
  "Hope",
  "The Rev. Dr. Martin Luther King, Jr.",
  "A micro-penis",
  "My soul",
  "A hot mess",
  "Vikings",
  "Hot people",
  "Seduction",
  "An Oedipus complex",
  "Geese",
  "Global warming",
  "New Age music",
  "Hot Pockets",
  "Making a pouty face",
  "Vehicular manslaughter",
  "Women's suffrage",
  "A defective condom",
  "Judge Judy",
  "African children",
  "The Virginia Tech Massacre",
  "Barack Obama",
  "Asians who aren't good at math",
  "Elderly Japanese men",
  "Exchanging pleasantries",
  "Heteronormativity",
  "Parting the Red Sea",
  "Arnold Schwarzenegger",
  "Road head",
  "Spectacular abs",
  "Figgy pudding",
  "A mopey zoo lion",
  "A bag of magic beans",
  "Poor life choices",
  "My sex life",
  "Auschwitz",
  "A snapping turtle biting the tip of your penis",
  "A thermonuclear detonation",
  "The clitoris",
  "The Big Bang",
  "Land mines",
  "Friends who eat all the snacks",
  "Goats eating cans",
  "The Dance of the Sugar Plum Fairy",
  "Jerking off into a pool of children's tears",
  "Man meat",
  "Me time",
  "The Underground Railroad",
  "Poorly-timed Holocaust jokes",
  "A sea of troubles",
  "Lumberjack fantasies",
  "Morgan Freeman's voice",
  "Women in yogurt commercials",
  "Natural male enhancement",
  "Being a motherfucking sorcerer",
  "Genital piercings",
  "Passable transvestites",
  "Sexy pillow fights",
  "Balls",
  "Grandma",
  "Friction",
  "Party Poopers",
  "Farting and walking away",
  "Being a dick to children",
  "Booby-trapping the house to foil burglars",
  "The Tempur-Pedic Swedish Sleep System",
  "Dying",
  "Hurricane Katrina",
  "The gays",
  "The folly of man",
  "Men",
  "Passive-aggressive Post-it notes",
  "Pterodactyl eggs",
  "Team-building exercises",
  "A brain tumor",
  "Cards Against Humanity",
  "Fear itself",
  "Lady Gaga",
  "The milk man",
  "A foul mouth",
  "A big black dick",
  "A beached whale",
  "A bloody pacifier",
  "A crappy little hand",
  "A low standard of living",
  "A nuanced critique",
  "Panty raids",
  "A passionate Latino lover",
  "A rival dojo",
  "A web of lies",
  "A woman scorned",
  "Clams",
  "Apologizing",
  "Appreciative snapping",
  "Neil Patrick Harris",
  "Beating your wives",
  "Being a dinosaur",
  "Shaft",
  "Bosnian chicken farmers",
  "Nubile slave boys",
  "Carnies",
  "Coughing into a vagina",
  "Suicidal thoughts",
  "Dancing with a broom",
  "Deflowering the princess",
  "Dorito breath",
  "Eating an albino",
  "Enormous Scandinavian women",
  "Fabricating statistics",
  "Finding a skeleton",
  "Gandalf",
  "Inappropriate yodeling",
  "George Clooney's musk",
  "Getting abducted by Peter Pan",
  "Getting in her pants, politely",
  "Gladiatorial combat",
  "Good grammar",
  "Hipsters",
  "Historical revisionism",
  "Insatiable bloodlust",
  "Jafar",
  "Jean-Claude Van Damme",
  "Just the tip",
  "Mad hacky-sack skills",
  "Leveling up",
  "Literally eating shit",
  "Making the penises kiss",
  "Media coverage",
  "Medieval Times Dinner and Tournament",
  "Moral ambiguity",
  "My machete",
  "One thousand Slim Jims",
  "Ominous background music",
  "Overpowering your father",
  "Pistol-whipping a hostage",
  "Quiche",
  "Quivering jowls",
  "Revenge fucking",
  "Ripping into a man's chest and pulling out his still-beating heart",
  "Ryan Gosling riding in on a white horse",
  "Santa Claus",
  "Scrotum tickling",
  "Sexual humiliation",
  "Sexy Siamese twins",
  "Slow motion",
  "Space muffins",
  "Statistically validated stereotypes",
  "Sudden Poop Explosion Disease",
  "The boners of the elderly",
  "The economy",
  "The Fanta girls",
  "The Gulags",
  "The harsh light of day",
  "Old-people smell",
  "The shambling corpse of Larry King",
  "The four arms of Vishnu",
  "Being a busy adult with many important things to do",
  "Tripping balls",
  "Cuddling",
  "Zeus's sexual appetites",
  "Ladies' underwear purchased from a vending machine",
  "Laughing at orphans",
  "Lesbian stripper ninjas",
  "Lolcats",
  "Losing your virginity to someone you just met at a frat party",
  "Lying to a girl to get her to put out",
  "Lying to terminally ill children about their life expectancy",
  "Lyme Disease",
  "M-m-m-mocking st-st-st-stutterers",
  "Making a girl pay on the first date",
  "Making love to a really sexy sheep",
  "Male pregnancy",
  "Man Boobs",
  "Masturbating With Glue",
  "Me in a thong",
  "Mecha-Hitler",
  "Mel Gibson's sanity",
  "Metal Gear",
  "Michigan",
  "Mistaking a retarded person for someone who's merely deaf",
  "Misunderstood pedophiles",
  "Mocking autistic children because they don't have feelings",
  "Monkeys Fucking",
  "Mother Theresa's rotting corpse",
  "Motherfucking Cthulhu",
  "Muhammed Ali",
  "Muscles",
  "Muslims",
  "My dick in a box",
  "My hopes and dreams",
  "NCIS Fanfiction",
  "Never being able to look your dog in the eyes again",
  "New England Clam Chowder",
  "Nicholas Cage's storied career",
  "Not knowing the difference between trolling and being wrong",
  "Not using enough lube",
  "NPR",
  "Nude wrestling",
  "Nuns",
  "Object-sexuals",
  "Off-duty Nazis just looking for a good time",
  "Old ladies paying by check",
  "Old Man Penis",
  "Old people having loud sex",
  "Cryogenically frozen testicles",
  "2 Girls 1 Cup",
  "50 Shades of Grey",
  "70's bush",
  "A 60 year old who is hot in a weird way",
  "A Bag of Milky Ways",
  "A bar-mitzvah",
  "A beat so fresh, it just might destroy the universe",
  "A bitch slap",
  "A bitchy email from your boss",
  "A black hole",
  "A black-and-white episode of 'Gilligan's Island'",
  "A box full of terrible foreign candy",
  "A bucket of angry tiger cubs",
  "A bushy mustache",
  "A car trunk full of hot, glistening tripe",
  "A chainmail bikini",
  "A cheap motel",
  "A cheesy discharge",
  "A cripple fight",
  "A crippled albino midget",
  "A crying stripper",
  "A day care Fight Club",
  "A dead hooker",
  "A dildo",
  "A dude in a thong",
  "A failed abortion",
  "A fat ass in spandex",
  "A foul mouthed Furby",
  "A freshly waxed handle bar mustache",
  "A gas station bathroom",
  "A glass jar with a preserved two-headed fetal pig",
  "A gold digger",
  "A grown man crying at a movie",
  "A Hello Kitty vibrator",
  "A hilarious failed suicide attempt",
  "A horse with a boner",
  "A husband",
  "A man pretending to be a woman's 'gay friend' in order to get at that sweet vadge",
  "A man shot over a game of dominoes",
  "A man-sized hamster wheel",
  "A Maury Povitch paternity test",
  "A millionaire with a heart of gold",
  "A molester mustache",
  "A monolith",
  "A ninja with diarrhea",
  "A pack of Mentos and a two-liter bottle of Diet Coke",
  "A pearl necklace",
  "A person who is a douche but still hot",
  "A piñata full of scorpions",
  "A porn star with daddy issues",
  "A prosthetic leg",
  "A racist uncle",
  "A really ugly baby",
  "A rubber snake",
  "A rusty trombone",
  "A sadistic dentist",
  "A self-fulfilling prophecy",
  "A suspiciously convenient plot device",
  "A televangelist getting caught picking up male prostitutes",
  "A time machine",
  "A toddler-sized coffin",
  "A tramp stamp",
  "A vintage collection of Kirk-Spock slashfic",
  "A wet willy",
  "A wheelchair death race",
  "A whiny Taylor Swift song about a guy screwing her over",
  "A wife",
  "A wisecracking terrorist",
  "A wizard's sleeve",
  "A woman scorned",
  "A woman scorned ",
  "A yeast infection",
  "Accidentally sexting your mom",
  "Adult diapers",
  "Adult friendfinder",
  "Amputee sex",
  "An attractive midget",
  "An awkward boner",
  "An Explosion of Juices in My Mouth",
  "An uncomfortably attractive pre-op tranny",
  "Anal Leakage",
  "Anal warts",
  "Anne Frank",
  "Anyone who puts Baby in a corner",
  "Asians",
  "Asians being racist against each other",
  "Asking her when she's due and finding out she's not pregnant",
  "Ass-to-mouth",
  "Assholes",
  "Assuming all handicapped people are retarded",
  "Atheists and agnostics",
  "Attending church",
  "Autistic Kids",
  "Autoerotic asphyxiation",
  "Baby pigs wearing people clothes",
  "Back hair",
  "Band geeks",
  "Barely 18 Chaz Bono",
  "Bath salts",
  "Bea Arthur’s Saggy Boobs",
  "Bears",
  "Beating Rodney King",
  "Because Fuck You, That's Why",
  "Becoming a Junior High Chess Champion for the sweet hook-ups",
  "Becoming what you hate",
  "Bedbugs",
  "Beef",
  "Beer Farts",
  "Being 'a little pregnant'",
  "Being friends with someone who is awful, but frequently picks up the check at dinner",
  "Being happy you just made a gay friend so you can use the phrase 'my gay friend'…",
  "Being Raped By A Moose",
  "Being turned on by phallic vegetables",
  "Being uncomfortable realizing you're outnumbered by members of another race",
  "Belly Button Lint",
  "Biggest Losers",
  "Bin Laden",
  "Binders full of women",
  "Black Jesus",
  "Blacking out",
  "Blood diamonds",
  "Bloody poop",
  "Blue Waffle",
  "Boobs that sag down to her knees",
  "Botched facelift",
  "Botulism",
  "Boy bands",
  "Breaking into a zoo to steal a monkey",
  "Breast Cancer",
  "Breath so bad that your butt is mad at your mouth",
  "Bunnies",
  "Burning in hell",
  "Burning when you pee",
  "Butt acne",
  "Butt Hair",
  "Butter",
  "Butthurt",
  "Canned tuna with extra dolphin",
  "Cards Against Humanity",
  "Carrot Top's pecs",
  "Cartoon pussy",
  "Celebrity beaver shot",
  "Cellophane underwear",
  "Charlie Sheen",
  "Childrens' crutches",
  "Chimpanzees with anger management issues",
  "Chris Farley seductively rubbing his nipples",
  "Chubby Chasers",
  "Chuck Norris",
  "Chunks of dead prostitute",
  "Classic Mickey Mouse porn",
  "Clubbing baby seals",
  "Consensual rape",
  "Cookies and kittens",
  "Cousin cuddling",
  "Cracking your knuckles",
  "Cripple Fight",
  "Crotchless toddler underwear",
  "Sticking a fork in an electrical socket",
  "One trillion dollars",
  "Oprah's Va-Jay-Jay",
  "Our homeless veterans",
  "Paris Hilton",
  "PCP",
  "Pedophilia",
  "Penguin orgy",
  "Penis implants",
  "People who smell their own socks",
  "Performing sex acts learned from Urban Dictionary",
  "Pirate customer service representatives",
  "Pizza, Pot and Porn",
  "Pooping in the soup",
  "Popeye's Chicken",
  "Prison Rape",
  "Prosti-tots",
  "Public restrooms",
  "Puns that aren't funny",
  "Putting out on the first date",
  "Putting the 'fun' in 'fundamentalism'",
  "Putting wheel locks on wheelchairs",
  "Queen Latifah",
  "Quoting Monty Python",
  "Randy gerbils totally macking you",
  "Reading Rainbow",
  "Realdoll owners",
  "Reality television",
  "Realizing too late that there's no toilet paper left",
  "Reparations for slavery",
  "Richard simmons in a pink sparkly tanktop",
  "Riding the short bus",
  "Robbing a sperm bank",
  "Rock-Paper-Scissors-Lizard-Spock",
  "Rodent feces",
  "Ron Jeremy's penis",
  "Rotting elk carcasses",
  "Rusty Trombone",
  "Salmonella",
  "Sand in My Vagina",
  "Saying 'I disapprove of what you say, but I will defend to the death your right to say it' when you know you wouldn't",
  "Seabirds strangled by plastic six-pack rings",
  "Secondhand adult diapers",
  "Self-diagnosed Asperger's Syndrome sufferers",
  "Semen",
  "Sex with vegetables",
  "Sexual experimentation in college",
  "Shaken Baby Syndrome",
  "Sharting",
  "Sheep",
  "Showing up to an orgy for the food",
  "Sipping artificial popcorn butter",
  "Slaughtering innocent children",
  "Slavery",
  "Slutty nuns",
  "Smelly hippies",
  "Smelly Vaginas",
  "Smurf-on-smurfette action",
  "Snitching",
  "Snookis Vagina",
  "Speaking English instead of American",
  "Squirrel-on-whale action",
  "Starting a cult for tax breaks",
  "Stealing Babies ",
  "Stealing Wheelchairs",
  "Stepping in gum",
  "Stepping on a hairball with a bare foot",
  "Stigmata",
  "Stormtroopers",
  "Stunt cock",
  "Suburban chain restaurants",
  "Sucking some dicks to not get drafted",
  "Suicidal Foxconn employees",
  "Swingers",
  "Synchronized Sneezing",
  "Syrup Sex",
  "Taking a dump in the ball pit at Chuck E Cheese",
  "Taking body shots off your mom",
  "Taking fantasy football way too seriously",
  "Teen Pregnancy",
  "Telling a nun to eat a dick",
  "Texas Sleigh Rides",
  "Thai Lady Boys",
  "That 'not-so-fresh' feeling",
  "That crazy bitch you work with",
  "That feeling when you encounter a handicapped person waiting for you to leave the largest stall in a restroom",
  "That guy who is pretty much a dick but you're still friends with him anyway",
  "That stuff between your toes",
  "The 911 Truther movement",
  "The ancient martial art of Flung Poo",
  "The Boy Scouts of America",
  "The cast of Jersey Shore",
  "The Challenger explosion",
  "The CIA selling crack in the inner-city",
  "The Civil War",
  "The Dick in My Mouth",
  "The drama club",
  "The dreams of a child",
  "The entire Mormon Tabernacle Choir",
  "The female orgasm",
  "The harsh day of light",
  "The Holy Grail",
  "The Human Centipede",
  "The Jonestown cult suicides",
  "The Kardashian sisters",
  "The Knights Who Say 'Ni'!",
  "The lonliest Brony",
  "The Maury Show",
  "The orchestra that played as the Titanic went down",
  "The Red Menace",
  "The rich pageantry of Macy's Thanksgiving Day Parade",
  "The Ron Popeil Pocket Fisherman",
  "The second time I got crabs",
  "The Spanish Inquisition",
  "The Tea Party",
  "The three wise men",
  "The two actors who played Darren Stevens in 'Bewitched'",
  "The wet spot on the bed",
  "This is a test",
  "This is what I'm saying!",
  "Three and a half babies",
  "Three Asian strippers, two porn stars, and a suitcase full of blow",
  "Throwing a virgin into a volcano",
  "Throwing Poop like a Monkey",
  "Throwing up in your mouth",
  "Tickle Me Elmo",
  "Time travel",
  "Toast with the burned image of Our Lord and Savior, Jesus Christ",
  "Toenail fungus",
  "Tossing Salad",
  "Traveling back in time to become your own grandparent",
  "Triangle Bush",
  "Trying to be nice while describing a friend's ugly baby",
  "Tuna noodle casserole",
  "Twincest",
  "Ugly Mexican hookers",
  "Unconditional love",
  "Underage cosplayers in bondage gear",
  "Unidentifiable spots on your dick",
  "Unironic Tebowing",
  "Vagina dentata",
  "Victims of lead-based paint",
  "Vorpal Dildo of Enlightenment +2",
  "War crimes",
  "Watching a Twilight movie on purpose",
  "Wearing extra thin pants for a strip club lap dance",
  "Wearing the genitals of a defeated enemy around your neck as a trophy",
  "White Trash",
  "Wolf-whistling at Girl Scouts",
  "Women",
  "Wondering if it was something you did which caused your significant other to become gay",
  "Wondering if the colorblind have an equally useless superpower",
  "World Series of Felching",
  "Yellow snow",
  "You are a whore",
  "Your ass hurting from wiping too much",
  "Your aunt barging into the bathroom when you're pooping",
  "Your face",
  "Zombie consultants",
  "Zyklon B",
];
const blackList = [
  "Next time on Dr. Phil: How to talk to your child about _____.",
  "Only two things in life are certain: death and _____.",
  "Everyone down on the ground! We don't want to hurt anyone. We're just here for _____.",
  "The healing process began when I joined a support group for victims of _____.",
  "The votes are in, and the new high school mascot is _____.",
  "Charades was ruined for me forever when my mom had to act out _____.",
  "Tonight on 20/20: What you don't know about _____ could kill you.",
  "During his midlife crisis, my dad got really into _____.",
  "My new favorite porn star is Joey '_____' McGee.",
  "Before I run for president, I must destroy all evidence of my involvement with _____.",
  "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
  "In his newest and most difficult stunt, David Blaine must escape from _____.",
  "The Five Stages of Grief: denial, anger, bargaining, _____, acceptance.",
  "Members of New York's social elite are paying thousands of dollars just to experience _____.",
  "This month's Cosmo: 'Spice up your sex life by bringing _____ into the bedroom.'",
  "Little Miss Muffet Sat on a tuffet, Eating her curds and _____.",
  "My country, 'tis of thee, sweet land of _____.",
  "After months of debate, the Occupy Wall Street General Assembly could only agree on 'More _____!'",
  "But before I kill you, Mr. Bond, I must show you _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "Dear Abby, I'm having some trouble with _____ and would like your advice.",
  "Due to a PR fiasco, Walmart no longer offers _____.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____.",
  "During sex, I like to think about _____.",
  "He who controls _____ controls the world.",
  "How am I maintaining my relationship status?",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with _____.",
  "I drink to forget _____.",
  "I got 99 problems but _____ ain't one.",
  "I learned the hard way that you can't cheer up a grieving friend with _____.",
  "I never truly understood _____ until I encountered _____.",
  "I wish I hadn't lost the instruction manual for _____.",
  "I'm sorry, Professor, but I couldn't complete my homework because of _____.",
  "In 1,000 years, when paper money is but a distant memory, _____ will be our currency.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____.",
  "In his new self-produced album, Kanye West raps over the sounds of _____.",
  "What's that sound?",
  "What's the crustiest?",
  "What's the gift that keeps on giving?",
  "What's the most emo?",
  "What's the new fad diet?",
  "What's the next Happy Meal toy?",
  "What's the next superhero/sidekick duo?",
  "What's there a ton of in heaven?",
  "When all else fails, I can always masturbate to _____.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.",
  "When I am President of the United States, I will create the Department of _____.",
  "When I pooped, what came out of my butt?",
  "When I'm in prison, I'll have _____ smuggled in.",
  "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
  "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____.",
  "White people like _____.",
  "Who stole the cookies from the cookie jar?",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?",
  "What am I lying to my friends about?",
  "What brought the orgy to a screeching halt?",
  "What did I find in the couch cushions?",
  "What do I fear my parents will find in my sock drawer?",
  "What do I like best about my job?",
  "What do I think about when I'm having trouble getting off? ",
  "What gave me aids?",
  "What goes best on toast?",
  "What I wouldn't give for 10 minutes alone with _____",
  "What in my past led to my current position on gun control laws?",
  "What is in my zombie apocalypse survival bag?",
  "What is the moral of the story?",
  "What is the only way I can achieve orgasm?",
  "What keeps me up at night?",
  "What makes Fred Phelps hard?",
  "What makes me tingle all over?",
  "What makes the world go round?",
  "What melts in your mouth, not in your hand?",
  "What time is it? _____ time!",
  "What was Abraham Lincoln's deep, dark secret?",
  "What will be an issue in the next presidential election?",
  "What will be our last chance for salvation when our new robot overlords take over?",
  "What will be put in the time capsule to preserve humanity's memory?",
  "What will I bring to the party?",
  "What's my superpower?",
  "What's the real reason that I've gathered you all hear today?",
  "What's the worst that could happen?",
  "When a man and a woman love each other very much, suddenly _____.",
  "When I get drunk, I feel that I am an expert on _____.",
  "When I get married, our vows will include words about _____.",
  "When I saw your mom naked, it reminded me of _____",
  "When I'm alone and the room is totally dark, I like to secretly _____.",
  "When you wake up from a night of heavy drinking, you usually regret _____",
  "Where do babies come from?",
  "Who could have guessed that the alien invasion would be easily thwarted by _____.",
  "Who was my childhood hero?",
  "Why am I in such a bad mood?",
  "Why am I like this?",
  "Why are we wearing tuxedos?",
  "Why does God pee on us, periodically?",
  "Why is mom calling?",
  "Why was my application to work at McDonald's rejected?",
  "With the Democrats and Republicans in a dead heat, the election was stolen by the _____ party.",
  "You can never have too many _____ when in East LA.",
  "You can never have too much _____.",
  "You know God hates you when _____.",
  "You’re in good hands with _____.",
  "Iron Chef: Today's secret ingredient is _____.",
  "It is often argued that our ancestors would have never evolved without the aid of _____.",
  "It sucks when you look in the fridge, and all you have to eat is _____.",
  "Jesus is _____.",
  "Keep your friends close, but your _____ closer.",
  "Kitten thinks of nothing but _____ all day.",
  "Like a good neighbor _____ is there.",
  "Loving you is easy 'cause you're _____.",
  "Mister Owl, how many licks does it take to get to the center of _____?",
  "Moral at work was boosted when they put_____ in the vending machines.",
  "Mr. Owl, how many licks does it take to get to the center of _____?",
  "My favorite childhood memory is_____.",
  "My favorite TV channel is the one that shows programs about _____.",
  "My Little Pony: Friendship is _____.",
  "My mission in life is to create a videogame about _____.",
  "My other car is a _____.",
  "New car sticker craze: Calvin pissing on _____.",
  "Next on Oprah, teens addicted to _____.",
  "Nobody puts _____ in a corner.",
  "Nothing beats cuddling with _____ in bed.",
  "Now witness the firepower of this fully armed and operational _____!",
  "On tonight's special report, _____. Fact or fiction?",
  "Only _____ is worse than a heretic.",
  "Our most powerful weapon on the day of the zombie apocalypse will be _____.",
  "Say no to _____.",
  "Science has discovered that beyond the edges of the universe, there is only _____.",
  "Scientists have reverse engineered alien technology that unlocks the secrets of _____.",
  "Something you should regret, but secretly don't.",
  "Sometimes you feel like _____, sometimes you don't.",
  "Sticks and stones may break my bones, but _____ will never hurt me.",
  "Stop staring at my _____.",
  "The 1930's is often regarded as the golden age of _____.",
  "The best Christmas present my grandma ever gave me was_____.",
  "The best part of waking up is _____ in your cup.",
  "The best things in life come in _____.",
  "The Christian Coalition has recently decided that an even worse sin than same-sex marriage is _____.",
  "The clown made all the children laugh with his balloon animal in the shape of _____.",
  "_____ ain't nothin' to fuck with.",
  "_____ good to the last drop.",
  "_____ in the morning, sailors take warning.",
  "_____ is a time-saving godsend for busy housewives.",
  "_____ is best enjoyed on the first date.",
  "_____ is dead to me.",
  "_____ is now outsourced to call centers in India.",
  "_____ is the name of my new indie black metal emo jazz post-dubstep funk band.",
  "_____ is the new black.",
  "_____ is the root of all evil.",
  "_____ isn't about sex, it's about power.",
  "_____ means never having to say you're sorry.",
  "_____ R Us.",
  "_____, for the win!",
  "_____, fun for the whole family!",
  "_____: The Other White Meat.",
  "_____. Because, fuck you, that's why.",
  "_____. I'd hit that.",
  "_____. It's everywhere you want to be.",
  "_____. The Care Bear Stare",
  "_____. The Final Frontier.",
  "_____. The Nicolas Cage Story",
  "_____. The other white meat.",
  "'Watson!' Holmes exclaimed, 'This man was obviously killed by _____!'",
  "2 things you need to survive on a deserted island",
  "9 out of 10 doctors agree, _____ twice a day prevents cancer.",
  "A fortune teller told me I will live a life filled with _____.",
  "A little-known fact is that Microsoft Windows was originally slated to be the first operating system to include _____.",
  "After Billy Mays died, he sold God _____.",
  "All the cool kids are doing it.",
  "And on his farm he had _____, e-i-e-i-o!",
  "And then little Billy woke up the next morning, he discovered that the tooth fairy had left _____ under his pillow.",
  "Apple has revealed they now have a patent for _____.",
  "Ask your doctor if _____ is right for you.",
  "Back in my day, _____ only cost a nickel.",
  "Check your privilege. And _____.",
  "Choosy moms choose _____.",
  "Cirque de Soleil presents MYSTIQUEE, a night of daring acrobatics, whimsy and _____.",
  "Daddy drinks because of _____.",
  "Damn it feels good to be _____.",
  "Danger! _____ ahead!",
  "Disney presents _____ on ice!",
  "Disney's newest Pixar movie will be about _____.",
  "For campaign funding reform to really be effective, there needs to be a specific policy about _____ contributions.",
  "Fred Phelps and his church have just announced that they plan to start picketing the funerals of _____ as well as gays.",
  "Genius is 10% inspiration and 90% _____.",
  "Give me liberty, or give me _____!",
  "Go-go Gadget _____!",
  "Groundbreaking research provides convincing evidence that _____ killed the dinosaurs.",
  "Happiness is _____.",
  "Horton could hear it through the bedroom wall...his mother and _____.",
  "Horton is always forcing his _____ on other people.",
  "I always call in sick to work when I have a bad case of _____.",
  "I always think of _____ when I fall asleep.",
  "I can handle public displays of affection, but _____ is really too much.",
  "I can't get no _____.",
  "I feel the need—the need for _____.",
  "I firmly believe that for the economy to recover, the Department of _____ needs to change its policies on _____.",
  "I for one welcome our new _____ overlords!",
  "I got a fever and the only cure is more _____.",
  "I have decided to commit to a life of studious contemplation on_____.",
  "I like my women like _____.",
  "I like to keep _____ as a souvenir of my sexual encounters.",
  "In an attempt to reach a wider audience, the Royal Ontario Museum has opened an interactive exhibit on _____.",
  "Air Canada guidelines now prohibit _____ on airplanes.",
  "O Canada, we stand on guard for _____.",
  "What's the Canadian government using to inspire rural students to succeed?",
  "In the next Bob and Doug McKenzie adventure, they have to find _____ to uncover a sinister plot involving _____ and _____.",
  "In Vancouver it is now legal to _____.",
  "After blacking out during New Year's Eve, I was awoken by _____.",
  "Every Christmas, my uncle gets drunk and tells the story about _____.",
  "Jesus is _____.",
  "This holiday season, Tim Allen must overcome his fear of _____ to save Christmas.",
  "On the third day of Christmas, my true love gave to me: three French hens, two turtle doves and _____.",
  "Wake up, America. Christmas is under attack by secular liberals and their _____.",
  "What keeps me warm during the cold, cold winter?",
];
const run = async () => {
  const whiteValus = whiteList
    .map((text) => {
      return `("white","${text}")`;
    })
    .join(",");
  const blackValus = blackList
    .filter((text) => {
      if (text.split("_____").length > 2) return;
      return text;
    })
    .map((text) => {
      return `("black","${text}")`;
    })
    .join(",");
  await insertCard(blackValus + "," + whiteValus);
};
run();
